In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [8]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [10]:
df.shape

(569, 31)

In [15]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [16]:
# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
X_train

array([[ 0.06994598,  1.79483341,  0.00356014, ..., -0.91739937,
        -0.92922016, -1.09414141],
       [-0.05631235, -0.54127699, -0.03063883, ...,  0.31902727,
         0.25832368, -0.26542496],
       [-1.26781841, -1.73518452, -1.28974471, ..., -1.75856867,
         0.31909702, -0.15774177],
       ...,
       [-0.60438828,  0.79129303, -0.55947164, ..., -0.10737888,
        -1.18216865,  0.50722964],
       [-0.52691158, -1.63647563, -0.55530103, ..., -0.33857569,
        -0.13752427, -0.92373555],
       [ 0.2708115 ,  0.62677821,  0.21250749, ...,  0.55491153,
        -0.3871877 , -0.31205066]])

In [18]:
y_train

462    B
255    M
140    B
546    B
26     M
      ..
35     M
470    B
382    B
170    B
54     M
Name: diagnosis, Length: 455, dtype: object

In [19]:
# Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [20]:
y_train

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,

In [ ]:
# Numpy arrays to PyYTorch tensors

In [63]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [44]:
X_train_tensor.shape

torch.Size([455, 30])

In [45]:
y_train_tensor.shape

torch.Size([455])

In [54]:
# Defining the Model
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64,requires_grad=True)


  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





In [59]:
# Importance Parameters
learning_rate = 0.1
epochs = 25

In [60]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.9677054688712188
Epoch: 2, Loss: 3.8425430808915926
Epoch: 3, Loss: 3.710560539165313
Epoch: 4, Loss: 3.5754059928588955
Epoch: 5, Loss: 3.432155681988966
Epoch: 6, Loss: 3.28230247536783
Epoch: 7, Loss: 3.121658841217554
Epoch: 8, Loss: 2.9565481305584647
Epoch: 9, Loss: 2.7887030852485917
Epoch: 10, Loss: 2.619795149697901
Epoch: 11, Loss: 2.4478997944192877
Epoch: 12, Loss: 2.2654083327583985
Epoch: 13, Loss: 2.0842903825298738
Epoch: 14, Loss: 1.9104713282849064
Epoch: 15, Loss: 1.7415620537438834
Epoch: 16, Loss: 1.578165938184646
Epoch: 17, Loss: 1.4276746981939543
Epoch: 18, Loss: 1.292154083557442
Epoch: 19, Loss: 1.173558530320644
Epoch: 20, Loss: 1.073385427041612
Epoch: 21, Loss: 0.9922018980153715
Epoch: 22, Loss: 0.9292277436257469
Epoch: 23, Loss: 0.882258706035767
Epoch: 24, Loss: 0.8481002440603924
Epoch: 25, Loss: 0.8233466868148862


In [61]:
model.bias

tensor([-0.1069], dtype=torch.float64, requires_grad=True)

In [64]:

# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6680517196655273
